
// #############################################################################
// #                                                                           #
// #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
// #                                                                           #
// #############################################################################


import Foundation
import NIO

extension EventLoopFutureNetworking {

  @inlinable
  public func eventLoopFutureRaw<E>(_ endpoint: E) -> EventLoopFuture<RawResponse> where E: Endpoint {
    do {
      return eventLoopFuture(try request(endpoint))
    } catch {
      return eventLoop.makeFailedFuture(error)
    }
  }

  public func eventLoopFuture<E>(_ endpoint: E) -> EventLoopFuture<EndpointResponse<E>> where Self: Sendable, E: Endpoint & Sendable, E.ResponseBody: Decodable {
    eventLoopFutureRaw(endpoint)
      .flatMapThrowing { rawResponse -> EndpointResponse<E> in
        try endpoint.validate(networking: self, response: rawResponse)
        return (
          rawResponse.response,
          .init { try self.decode(contentType: endpoint.acceptType, body: rawResponse.body) }
        )
      }
  }
  
  public func eventLoopFuture<E>(_ endpoint: E) -> EventLoopFuture<EndpointResponse<E>> where Self: Sendable, E: Endpoint & Sendable, E.ResponseBody: CustomResponseBody {
    eventLoopFutureRaw(endpoint)
      .flatMapThrowing { rawResponse -> EndpointResponse<E> in
        try endpoint.validate(networking: self, response: rawResponse)
        return (
          rawResponse.response,
          .init { try self.decode(body: rawResponse.body) }
        )
      }
  }
  
}
